Repository CIrcle0616/global_nomad, pull requests merged in 2025-05, with the labels that each got.

#3 feat: global.css 스타일 추가
  app/globals.css
  tailwind.config.ts
Labels: 기능

#8 [Docs] 프로젝트 PR 템플릿 작성
  .github/pull_request_template.md
Labels: 문서

#20 [Docs] 프로젝트 PR 템플릿 수정1
  .github/pull_request_template.md
Labels: :page_facing_up: Docs

#33 [Fix] api 요청 BASE_URL 수정
  services/activities.ts
  services/auth.ts
  services/fetchWrapper.ts
  services/myActivities.ts
  services/myNotifications.ts
  services/myReservations.ts
  services/oauth.ts
  services/users.ts
Labels: :bug: Bug, :wrench: Chore

#32 [Feat] 프로필 레이아웃 구현 및 반응형 추가
  app/profile/layout.tsx
  app/profile/reservations/page.tsx
  components/layout/ProfileLayout.tsx
  components/layout/SideProfile.tsx
  package-lock.json
  public/ic_account_check.svg
  public/ic_account_gray.svg
  public/ic_calendar_check.svg
  public/ic_calendar_gray.svg
  public/ic_cog.svg
  public/ic_cog_gray.svg
  public/ic_nofile.svg
  public/ic_pen.svg
  public/ic_textbox_check.svg
  public/ic_textbox_gray.svg
  tailwind.config.ts
Labels: :sparkles: Feature

#22 [Feat] 드롭다운 컴포넌트 최종 수정
  components/common/DropDown.tsx
  components/common/DropDownSelect.tsx
  components/common/Input.tsx
Labels: :sparkles: Feature

#34 [Feat] Common button 컴포넌트 수정
  components/common/CommonButton.tsx
Labels: :sparkles: Feature

#41 [Feat] empty-page UI 및 반응형 추가
  app/profile/activities/page.tsx
  app/profile/info/page.tsx
  app/profile/reservations/page.tsx
  app/profile/schedule/page.tsx
  components/empty/EmptyState.tsx
  components/layout/ProfileLayout.tsx
  components/layout/SideProfile.tsx
  public/ic_empty.svg
Labels: :sparkles: Feature, :lipstick: Style

#39 [Feat] modal 로직 수정
  app/layout.tsx
  components/common/GlobalModal.tsx
  components/common/ModalTest.tsx
  components/common/OneButtonModal.tsx
  components/common/TwoButtonModal.tsx
  store/ModalStore.tsx
  store/OneButtonModalStore.tsx
  store/index.js
Labels: :sparkles: Feature
