Repository CIrcle0616/global_nomad, pull requests merged in 2025-06, with the labels that each got.

#45 [Feat] 로그인/회원가입 페이지 구현 (Oauth x, 쿠키 x, 로그인 정보 -> 로컬스토리지 저장)
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/layout.tsx
  app/provider.tsx
  components/domain/auth/AuthLogo.tsx
  components/domain/auth/HrWithText.tsx
  components/domain/auth/KakaoOauthLink.tsx
  components/domain/auth/LinkToSign.tsx
  components/domain/auth/LoginForm.tsx
  components/domain/auth/SignUpForm.tsx
  package-lock.json
  package.json
  public/ic_passwordOff.svg
  public/ic_passwordOn.svg
  public/img_kakao.svg
  public/img_logoBig.svg
  services/activities.ts
  services/auth.ts
  services/index.js
  services/myActivities.ts
  services/myNotifications.ts
  services/myReservations.ts
  services/oauth.ts
  services/users.ts
  store/useAuthStore.ts
Labels: :sparkles: Feature

#52 [Feat] 예약 내역 리스트 UI 구현(목업 데이터)
  app/profile/reservations/page.tsx
  components/common/DropDown.tsx
  components/common/ReservationCard.tsx
  components/skeleton/SkeletonCard.tsx
  constants/filterOption.ts
  constants/reservationsMock.ts
  constants/statusMap.ts
  public/ic_vector.svg
Labels: :sparkles: Feature

#46 [Feat] 스토리북 설치, 설정 변경, 스토리북 컴포넌트 추가
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  components/stories/CommonButton.stories.tsx
  components/stories/DatePicker.stories.tsx
  components/stories/DropDown.stories.tsx
  components/stories/DropDownSelect.stories.tsx
  components/stories/Footer.stories.tsx
  components/stories/Input.stories.tsx
  package.json
Labels: :sparkles: Feature

#58 [Feat] 이메일 중복체크, 모달 연결, 커스텀 에러
  components/domain/auth/LoginForm.tsx
  components/domain/auth/SignUpForm.tsx
  constants/utils/errors.ts
  services/fetchWrapper.ts
Labels: :sparkles: Feature

#63 [Feat] 모달파일 이동 및 글로벌 모달에 기능 추가, 좀 더 자유롭게 모달컴포넌트를 받게 함
  app/layout.tsx
  components/common/GlobalModal.tsx
  components/common/OneButtonModal.tsx
  components/common/TwoButtonModal.tsx
  components/common/index.js
  components/common/modal/GlobalModal.tsx
  components/common/modal/ModalTest.tsx
  components/common/modal/OneButtonModal.tsx
  components/common/modal/TwoButtonModal.tsx
  package-lock.json
  store/ModalStore.tsx
  store/index.js
  store/modalStore.ts
Labels: :sparkles: Feature, :recycle: Refactor

#67 [Feat] 체험 상세 수정/삭제 Dropdown 연결
  components/domain/activityDetail/ActivityDetailHeader.tsx
  components/domain/activityDetail/DropdownActivityDetail.tsx
  package-lock.json
  public/ic_kebab_menu.svg
Labels: :sparkles: Feature

#65 [Feat] 예약 내역 리스트 페이지 API로 데이터 불러오기
  app/profile/reservations/page.tsx
  components/common/ReservationCard.tsx
  components/domain/reservation/ClientReservations.tsx
  components/empty/EmptyState.tsx
  constants/reservationsMock.ts
  package-lock.json
Labels: :recycle: Refactor

#71 [Fix] 리액트 버전 19->18로 다운그레이드
  package-lock.json
  package.json
Labels: :bug: Bug

#73 [Feat] 카카오 로그인 연결 반환되는 토큰 쿠키로 세팅
   env.d.ts
  app/oauth/callback/client-processing/page.tsx
  app/oauth/kakao/route.ts
  components/domain/auth/KakaoOauthLink.tsx
  components/domain/auth/LoginForm.tsx
  components/domain/auth/SignUpForm.tsx
  lib/index.js
  services/fetchWrapper.ts
Labels: :sparkles: Feature

#72 [Feat] 체험 상세 이미지 섹션 구현
  components/domain/activityDetail/ActivityDescription.tsx
  components/domain/activityDetail/ActivityDetailHeader.tsx
  components/domain/activityDetail/ActivityImgSection.tsx
  components/domain/activityDetail/ActivityMap.tsx
  components/domain/activityDetail/ModalImgViewer.tsx
  package-lock.json
  package.json
  public/ic_pagination_arrow_left.svg
  public/ic_pagination_arrow_right.svg
  tailwind.config.ts
Labels: :sparkles: Feature

#75 [Feat] 내정보 페이지 작업
  app/profile/info/page.tsx
  components/domain/profile/MyInfoForm.tsx
  services/users.ts
Labels: :sparkles: Feature

#76 [Feat] 예약 내역 리스트 페이지 취소 버튼, 후기 모달, 무한 스크롤 구현
  app/profile/reservations/page.tsx
  components/common/modal/GlobalModal.tsx
  components/domain/reservation/ClientReservations.tsx
  components/domain/reservation/ReservationCard.tsx
  components/domain/reservation/ReviewForm.tsx
  components/domain/reservation/ReviewModal.tsx
  components/domain/reservation/StarRating.tsx
  public/ic_star.svg
  public/ic_star_yellow.svg
  public/ic_x_40.svg
  tailwind.config.ts
  types/domain/myReservations/types.ts
Labels: :sparkles: Feature, :recycle: Refactor

#79 [FIX]: 내 체험 리스트만 보이게 수정
  app/profile/activities/page.tsx
  components/domain/activity/ActivityCard.tsx
  components/domain/activity/MyActivityList.tsx
Labels: :sparkles: Feature

#83 [Fix] 무한 스크롤 및 API 호출(queryFn, patch, post) 로직 수정
  components/domain/reservation/ClientReservations.tsx
  components/domain/reservation/ReservationCard.tsx
  components/domain/reservation/ReviewForm.tsx
  hooks/useObserver.ts
Labels: :bug: Bug, :lipstick: Style

#95 [Feat]: 일정 겹치게 만들면 차단 기능 구현
  app/profile/activities/new/page.tsx
Labels: :sparkles: Feature

#93 [Feat]: 주소창 daum api 연결
  app/profile/activities/new/page.tsx
  package-lock.json
  package.json
Labels: :sparkles: Feature

#101 [Fix]: 병합충돌 처리를 잘못했는데 복구하였음
  app/profile/activities/new/page.tsx
Labels: :bug: Bug

#104 [Hotfix] 환경 변수 반영하도록 수정
  services/fetchWrapper.ts
Labels: :bug: Bug, :wrench: Chore

#97 [Feat] 메인페이지-인기항목, 검색, 정렬, 카테고리 탭
  app/layout.tsx
  app/page.tsx
  components/common/Container.tsx
  components/common/icons/ChevronIcon.tsx
  components/domain/activity/Search.tsx
  components/domain/activity/index.js
  components/domain/mainPage/MainPageActivityImg.tsx
  components/domain/mainPage/MainPageActivityListSection.tsx
  components/domain/mainPage/PopularActivitySection.tsx
  components/domain/mainPage/SearchBar.tsx
  components/domain/mainPage/SearchHeader.tsx
  components/domain/mainPage/activityList/MainActivityDescription.tsx
  components/domain/mainPage/activityList/MainActivityList.tsx
  components/domain/mainPage/activityList/MainPageBasicActivity.tsx
  components/domain/mainPage/activityList/taps/CategoryTabs.tsx
  components/domain/mainPage/activityList/taps/SortDropdown.tsx
  components/domain/mainPage/activityList/taps/TabList.tsx
  components/domain/mainPage/mainBanner/BannerDescription.tsx
  components/domain/mainPage/mainBanner/BannerImage.tsx
  components/domain/mainPage/mainBanner/MainPageBanner.tsx
  components/domain/mainPage/popularActivities/Gradation.tsx
  components/domain/mainPage/popularActivities/ListControl.tsx
  components/domain/mainPage/popularActivities/MainPagePopularActivity.tsx
  components/domain/mainPage/popularActivities/OverlayDescription.tsx
  components/domain/mainPage/popularActivities/PopularActivityList.tsx
  constants/filterOption.ts
  constants/index.js
  hooks/index.js
  hooks/useIsClient.ts
  hooks/useMainActivityList.ts
  hooks/usePopularActivities.ts
  hooks/useUpdateSearchParams.ts
  lib/getKoreanJosa.ts
  lib/provider.tsx
  public/ic_DEMO.svg
  public/ic_activity_star.svg
  public/img_DEMO.png
Labels: :sparkles: Feature

#99 [Feat] 프로필 이미지 업로드, 내정보 수정
  components/common/Input.tsx
  components/common/ProfileImageUploader.tsx
  components/domain/profile/MyInfoForm.tsx
  components/layout/SideProfile.tsx
  hooks/useProfileImageUpload.ts
Labels: :sparkles: Feature

#100 style: 공통 버튼 컴포넌트 스타일 수정
  components/common/CommonButton.tsx
Labels: :lipstick: Style

#106 [Feat] 체험등록 기능 추가
  app/profile/activities/new/page.tsx
  services/activities.ts
Labels: :sparkles: Feature

#108 [Feat] 커스텀 404 페이지 구현
  app/not-found/page.tsx
  components/common/NotFoundPage.tsx
  public/Ic_error_sand.png
  public/Ic_tube.png
Labels: :sparkles: Feature

#112 [Feat] 체험 상세 페이지네이션 구현
  app/activities/[activityId]/page.tsx
  components/domain/activityDetail/ActivityDetailReview.tsx
  components/domain/activityDetail/ReviewPagination.tsx
Labels: :sparkles: Feature

#113 [Refactor] gnb, footer 적용 및 체험 현황 오류 수정
  app/layout.tsx
  app/profile/schedule/page.tsx
  components/common/Footer.tsx
  components/common/gnb/Gnb.tsx
  components/common/gnb/NotificationCard.tsx
  components/common/gnb/NotificationList.tsx
  components/domain/auth/LoginForm.tsx
  components/layout/ProfileLayout.tsx
  services/fetchWrapper.ts
  store/useUserStore.ts
Labels: :recycle: Refactor

#115 style: 카드 스타일 수정
  app/profile/activities/page.tsx
  components/domain/activity/ActivityCard.tsx
  components/domain/activityDetail/DropdownActivityDetail.tsx
Labels: :sparkles: Feature, :lipstick: Style

#111 fix: 내 체험 관리 오류 수정
  app/profile/activities/new/page.tsx
  components/common/modal/ModalTest.tsx
Labels: :bug: Bug

#118 [Refactor] 로그인/회원가입 페이지 리팩토링, 버그 수정
  app/(auth)/login/page.tsx
  components/domain/auth/FormInput.tsx
  components/domain/auth/LoginForm.tsx
  components/domain/auth/SignUpForm.tsx
  hooks/index.js
  hooks/useLogin.ts
  hooks/useSignUp.ts
  middleware.ts
  package-lock.json
  public/img_DEMO.png
Labels: :bug: Bug, :recycle: Refactor

#119 [Refactor] gnb, calendar 스타일 수정 및 기능 수정
  components/common/DropDown.tsx
  components/common/gnb/Gnb.tsx
  components/common/gnb/NotificationCard.tsx
  components/common/gnb/NotificationList.tsx
  components/common/gnb/NotificationPopover.tsx
  components/domain/schedule/CalendarContent.tsx
  components/domain/schedule/ScheduleName.tsx
  lib/parseKoreanDate.ts
Labels: :recycle: Refactor, :lipstick: Style

#121 [Refactor,Feat] 내정보, 프로필 이미지 업로드 수정 사항 반영
  app/profile/info/page.tsx
  app/profile/layout.tsx
  components/common/ProfileImageUploader.tsx
  components/domain/profile/MyInfoForm.tsx
  components/skeleton/SkeletonMyInfoForm.tsx
Labels: :recycle: Refactor

#122 release: 0.3.0 기능 수정사항 반영 6/16
  app/(auth)/login/page.tsx
  app/activities/[activityId]/page.tsx
  app/layout.tsx
  app/profile/activities/new/page.tsx
  app/profile/activities/page.tsx
  app/profile/info/page.tsx
  app/profile/layout.tsx
  app/profile/schedule/page.tsx
  components/common/DropDown.tsx
  components/common/Footer.tsx
  components/common/ProfileImageUploader.tsx
  components/common/gnb/Gnb.tsx
  components/common/gnb/NotificationCard.tsx
  components/common/gnb/NotificationList.tsx
  components/common/gnb/NotificationPopover.tsx
  components/common/modal/ModalTest.tsx
  components/common/spinners/ComponentSpinner.tsx
  components/common/spinners/PageSpinner.tsx
  components/domain/activity/ActivityCard.tsx
  components/domain/activity/Search.tsx
  components/domain/activityDetail/ActivityDetailReview.tsx
  components/domain/activityDetail/ActivityMap.tsx
  components/domain/activityDetail/ActivityMapFooter.tsx
  components/domain/activityDetail/DropdownActivityDetail.tsx
  components/domain/activityDetail/ReviewPagination.tsx
  components/domain/auth/FormInput.tsx
  components/domain/auth/LoginForm.tsx
  components/domain/auth/SignUpForm.tsx
  components/domain/profile/MyInfoForm.tsx
  components/domain/reservation/ClientReservations.tsx
  components/domain/reservation/ReservationCard.tsx
  components/domain/reservation/ReviewForm.tsx
  components/domain/schedule/CalendarContent.tsx
  components/domain/schedule/ScheduleName.tsx
  components/layout/ProfileLayout.tsx
  components/skeleton/SkeletonMyInfoForm.tsx
  hooks/index.js
  hooks/useLogin.ts
  hooks/useObserver.ts
  hooks/useSignUp.ts
  lib/parseKoreanDate.ts
  middleware.ts
  package-lock.json
  public/img_DEMO.png
  public/img_spinner.svg
  services/fetchWrapper.ts
  store/useUserStore.ts
Labels: :rocket: deploy

#123 hotfix: 배포 브랜치와 개발 브랜치 동기화
  app/profile/schedule/page.tsx
  components/common/gnb/NotificationCard.tsx
  components/common/gnb/NotificationList.tsx
  services/fetchWrapper.ts
Labels: :rocket: deploy

#124 hotfix: 로그아웃 로직 GNB에 추가
  components/common/gnb/Gnb.tsx
  components/common/gnb/ProfileButton.tsx
  hooks/useLogin.ts
Labels: :bug: Bug

#128 [Refactor] 체험 상세 페이지 리팩토링, 이미지 섹션 개선, Dropdown 아이디 수정
  app/activities/[activityId]/page.tsx
  components/domain/activityDetail/ActivityDescription.tsx
  components/domain/activityDetail/ActivityDetailReview.tsx
  components/domain/activityDetail/ActivityImgSection.tsx
  components/domain/activityDetail/ActivityMap.tsx
  components/domain/activityDetail/ActivityMobileImgView.tsx
  components/domain/activityDetail/ActivityPCImgView.tsx
  components/domain/activityDetail/ClickableImage.tsx
  components/domain/activityDetail/DropdownActivityDetail.tsx
  components/domain/activityDetail/ModalImgViewer.tsx
  components/domain/activityDetail/ReviewList.tsx
  components/domain/activityDetail/ReviewPagination.tsx
  public/ic_close_white.svg
Labels: :recycle: Refactor

#133 [Feat]내 체험 수정 페이지 구현
  app/profile/activities/[activityId]/edit/page.tsx
  services/fetchWrapper.ts
  services/myActivities.ts
Labels: :sparkles: Feature

#132 [Feat] 예약 모달 및 예약 캘린더 기능 개선
  app/(main)/profile/schedule/calendar/MyReservationCalendar.tsx
  components/domain/schedule/ReservationModal.tsx
  hooks/useAvailableSchedules.ts
  hooks/useReservationCount.ts
  hooks/useScheduleOptions.ts
  store/useReservationStore.ts
Labels: :sparkles: Feature, :lipstick: Style

#134 refactor: 내가 만든 체험일 경우 예약카드 안보이게 수정
  app/(main)/activities/[activityId]/page.tsx
  components/domain/activityDetail/reservation/ReservationClientWrapper.tsx
Labels: :recycle: Refactor

#136 feat: 내 체험관리 스켈레톤 추가
  app/(main)/profile/activities/page.tsx
Labels: :sparkles: Feature

#143 [Fix]: 케밥 버튼 스타일 수정 및 날짜 선택 버그 수정
  app/(main)/profile/activities/[activityId]/edit/page.tsx
  app/(main)/profile/activities/new/page.tsx
  components/domain/activity/ActivityCard.tsx
Labels: :bug: Bug

#141 [Feat] 카카오톡 공유 기능 추가
  app/layout.tsx
  components/domain/activityDetail/ActivityDetailHeader.tsx
  components/domain/activityDetail/ActivityImgSection.tsx
  components/domain/activityDetail/ActivityMapFooter.tsx
  components/domain/activityDetail/ActivityShareModal.tsx
  components/domain/activityDetail/KakaoScriptLoader.tsx
  components/domain/activityDetail/ModalImgViewer.tsx
  public/ic_link_copy.svg
  public/ic_share.svg
  types/kakao.d.ts
Labels: :sparkles: Feature, :recycle: Refactor

#150 [Fix]: 드롭다운 버튼 라이브러리를 사용하였음 npm install 요망 및 수정페이지 버그 수정
  app/(main)/profile/activities/[activityId]/edit/page.tsx
  app/(main)/profile/activities/new/page.tsx
  app/(main)/profile/activities/page.tsx
  app/api/proxy/image/route.ts
  components/domain/activityDetail/DropdownActivityDetail.tsx
  package-lock.json
  package.json
Labels: :bug: Bug, :lipstick: Style

#155 [Refactor] 예약 현황 페이지 최종 마무리 및 체험 상세 예약 파일 삭제
  app/(main)/profile/schedule/ScheduleClientInner.tsx
  app/(main)/profile/schedule/calendar/MyReservationCalendar.tsx
  components/domain/activity/reservation/ReservationPC.tsx
  components/domain/activity/reservation/parts/DateSelector.tsx
  components/domain/activity/reservation/parts/ParticipantSelector.tsx
  components/domain/activity/reservation/parts/PriceTotal.tsx
  components/domain/activity/reservation/parts/TimeSelector.tsx
  components/domain/schedule/ReservationModal.tsx
  components/skeleton/SkeletonCalendar.tsx
Labels: :recycle: Refactor

#156 feat: 쿼리키 추가, 오류 수정
  components/common/gnb/ProfileButton.tsx
  lib/queryKeys.ts
  public/ic_DEMO.svg
Labels: :sparkles: Feature, :bug: Bug

#157 release: 1.0.0 최종 배포버전 6/21
  app/(main)/profile/activities/[activityId]/edit/page.tsx
  app/(main)/profile/activities/new/page.tsx
  app/(main)/profile/schedule/ScheduleClientInner.tsx
  app/(main)/profile/schedule/calendar/MyReservationCalendar.tsx
  components/common/gnb/ProfileButton.tsx
  components/domain/activity/reservation/ReservationPC.tsx
  components/domain/activity/reservation/parts/DateSelector.tsx
  components/domain/activity/reservation/parts/ParticipantSelector.tsx
  components/domain/activity/reservation/parts/PriceTotal.tsx
  components/domain/activity/reservation/parts/TimeSelector.tsx
  components/domain/schedule/ReservationModal.tsx
  components/skeleton/SkeletonCalendar.tsx
  lib/queryKeys.ts
  public/ic_DEMO.svg
Labels: :rocket: deploy

#159 style: gnb, 메인, 회원가입 페이지 UI 수정
  app/(auth)/signup/page.tsx
  app/(main)/layout.tsx
  components/common/gnb/AlarmButton.tsx
  components/common/gnb/Gnb.tsx
  components/common/gnb/ProfileButton.tsx
  components/domain/activity/Search.tsx
  components/domain/mainPage/MainPageActivityListSection.tsx
  components/domain/mainPage/PopularActivitySection.tsx
  components/domain/mainPage/activityList/MainPagination.tsx
  components/domain/mainPage/activityList/taps/CategoryTabs.tsx
  components/domain/mainPage/activityList/taps/SortDropdown.tsx
  components/domain/mainPage/mainBanner/BannerDescription.tsx
  components/domain/mainPage/popularActivities/OverlayDescription.tsx
  tailwind.config.ts
Labels: :lipstick: Style

#161 style: 예약내역,예약 상세 페이지 UI 수정
  components/domain/activity/ActivityCard.tsx
  components/domain/activityDetail/reservation/ReservationClientWrapper.tsx
  components/domain/activityDetail/reservation/ReservationMobile.tsx
  components/domain/activityDetail/reservation/ReservationPC.tsx
  components/domain/activityDetail/reservation/ReservationTablet.tsx
  components/domain/reservation/ReservationCard.tsx
  components/skeleton/SkeletonCard.tsx
Labels: :lipstick: Style
